### ISSUE TITLE
table store error 

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/synapsebridgehelpers#18]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/synapsebridgehelpers/export_tables.py", line 461, in export_tables
    used = source)
  File "/usr/local/lib/python3.6/site-packages/synapsebridgehelpers/export_tables.py", line 122, in _store_dataframe_to_table
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/synapseclient/client.py", line 874, in store
    return obj._synapse_store(self)
  File "/usr/local/lib/python3.6/site-packages/synapseclient/table.py", line 1772, in _synapse_store
    return copied_self._update_self(syn)
  File "/usr/local/lib/python3.6/site-packages/synapseclient/table.py", line 1789, in _update_self
    linesToSkip=self.linesToSkip)
  File "/usr/local/lib/python3.6/site-packages/synapseclient/client.py", line 2898, in _uploadCsv
    return self._POST_table_transaction(schema, uploadRequest)
  File "/usr/local/lib/python3.6/site-packages/synapseclient/client.py", line 2906, in _POST_table_transaction
    response = self._waitForAsync(uri=uri, request=request)
  File "/usr/local/lib/python3.6/site-packages/synapseclient/client.py", line 2686, in _waitForAsync
    result = self.restGET(uri+'/get/%s' % async_job_id['token'], endpoint=endpoint)
  File "/usr/local/lib/python3.6/site-packages/synapseclient/client.py", line 3303, in restGET
    exceptions._raise_for_status(response, verbose=self.debug)
  File "/usr/local/lib/python3.6/site-packages/synapseclient/core/exceptions.py", line 149, in _raise_for_status
    raise SynapseHTTPError(message, response=response)
synapseclient.core.exceptions.SynapseHTTPError: 412 Client Error: 
Row id: 2 has been changed since last read.  Please get the latest value for this row and then attempt to update it again.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/at-home-pd/update_tables/update_tables.py", line 50, in <module>
    main()
  File "/root/at-home-pd/update_tables/update_tables.py", line 46, in main
    copy_file_handles = True)
  File "/usr/local/lib/python3.6/site-packages/synapsebridgehelpers/export_tables.py", line 466, in export_tables
    "to {}.".format(source, target)) from e
synapseclient.core.exceptions.SynapseHTTPError: There was an issue storing records from syn12492996 to syn20710121.
```

**Comment by philerooski** [comment]
Called with these parameters: 
```
substudy='Udall-superusers' 
participantsTable='syn20710121'
tableMapping='syn21990205'
```

**Comment by philerooski** [comment]
After a first pass, this error seems to be caused by the synapse client confusing the recordId index for an actual table index. Additionally, the client/platform issue involving storing pandas float64 values like -400.0 (which end up as float64 because of missing values in that column) to columns of type string (like `createdOnTimeZone`) seems to have been resolved. Once I have a new batch of records from Bridge to test on I will see if removing calls to `sanitize_table` and resetting the index before storing fixes the issues I've been having.
